---
title: "try2-random_forest"
output: html_document
---

##Algorithm Used 
random forest with 10-folds cross validation

##Data preprocessing
  1.  columns : PassengerId, Name, Ticket was omitted because in our opinion they are random and have no          influence on our result prediction.
  2.  column Cabin was omitted. random forest can't handle categorical predictors with more than 53
      categories. we made a couple of attempts using the dummyVars function but those attempts failed
      beacause the differnces of Cabin levels between train and test data frames - we just couldn't unite
      those categorical predictors (to many of them).
  3.  We also had a problem with the Na's and because the large amount of those cells-deleting the rows
      was not an option, so we used rfImpute function to complete the values both in train and test sets.

##Parameters initialization

we initialized a dataframe with the next possible tunning values:
  Number of variables randomly sampled as candidates at each split - 5 (.mtry)
  number of trees - 30
we used cross validation with 10 folds.

```{r setup}
#install.packages("randomForest")
library(randomForest)
#install.packages("caret")
library(caret)
knitr::opts_knit$set(root.dir = 'C:/Users/oleg/Desktop/Study/year5/semesterA/dataAnalys/HW2/Titanic')
set.seed(123)

traindf <- read.csv("train.csv",na.strings = "")
traindf$Survived<- as.factor(traindf$Survived)
traindf$Pclass<- as.factor(traindf$Pclass)
traindf <- traindf[,-c(1,4,9,11)]

testdf <-read.csv('test.csv',na.strings = "")
testdf$Pclass<- as.factor(testdf$Pclass)
ids<- testdf$PassengerId
testdf<- testdf[,-c(1,3,8,10)]

testdf.imputed <- rfImpute(Pclass ~ ., testdf)
traindf.imputed <- rfImpute(Survived ~ ., traindf)

control <- trainControl(method="cv", number=10)
metric <- "Accuracy"

library(randomForest)
grid=expand.grid(.mtry=c(5))
fit.rf <- train(Survived~., data=traindf.imputed, method="rf",ntree = 30,metric=metric, trControl=control,tuneGrid=grid)
predictions <- predict(fit.rf, testdf.imputed)
res <- cbind(PassengerId=ids,Survived=as.character(predictions))
write.csv(res,file="try2-randomForest.csv",row.names = F)


```
